# Update all the sections by editing the data.yml file inside _data folder.

# Site Settings
title: Resume | Byron Poschwatta
url: 'https://poschwatta.ca'
baseurl: '/resume' # TODO: Use relative_url Liquid filter in code (https://jekyllrb.com/docs/liquid/filters/)
description: Byron's online resume

theme_skin: ceramic # See _sass/skins
chrome_mobile_color: # Use hex colors (ex: #1976d2) or leave empty if you don't want a color for chrome mobile searchbar

# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed # http://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style

# Build settings
compress-site: yes # TODO: Needed?
encoding: "utf-8"

# Development Settings
port: 4000
host: 0.0.0.0
safe: false
